import {
  type Product,
  type Zone,
  type CategoryMeta,
  ProductCategory,
} from '@/types';

// ─── Categories ───────────────────────────────────────────────────────────────

export const CATEGORY_META: CategoryMeta[] = [
  {
    slug: ProductCategory.FruitsAndVegetables,
    label: 'Fresh Fruits & Vegetable',
    emoji: '🥦',
    bgColor: 'bg-green-50',
    textColor: 'text-green-700',
  },
  {
    slug: ProductCategory.CookingOilAndGhee,
    label: 'Cooking Oil & Ghee',
    emoji: '🫙',
    bgColor: 'bg-yellow-50',
    textColor: 'text-yellow-700',
  },
  {
    slug: ProductCategory.MeatAndFish,
    label: 'Meat & Fish',
    emoji: '🥩',
    bgColor: 'bg-red-50',
    textColor: 'text-red-700',
  },
  {
    slug: ProductCategory.BakeryAndSnacks,
    label: 'Bakery & Snacks',
    emoji: '🍞',
    bgColor: 'bg-orange-50',
    textColor: 'text-orange-700',
  },
  {
    slug: ProductCategory.DairyAndEggs,
    label: 'Dairy & Eggs',
    emoji: '🥚',
    bgColor: 'bg-amber-50',
    textColor: 'text-amber-700',
  },
  {
    slug: ProductCategory.Beverages,
    label: 'Beverages',
    emoji: '🥤',
    bgColor: 'bg-blue-50',
    textColor: 'text-blue-700',
  },
  {
    slug: ProductCategory.Pulses,
    label: 'Pulses',
    emoji: '🫘',
    bgColor: 'bg-stone-50',
    textColor: 'text-stone-700',
  },
  {
    slug: ProductCategory.Rice,
    label: 'Rice & Grains',
    emoji: '🌾',
    bgColor: 'bg-lime-50',
    textColor: 'text-lime-700',
  },
  {
    slug: ProductCategory.Noodles,
    label: 'Noodles & Pasta',
    emoji: '🍝',
    bgColor: 'bg-pink-50',
    textColor: 'text-pink-700',
  },
  {
    slug: ProductCategory.Chips,
    label: 'Chips & Crisps',
    emoji: '🍟',
    bgColor: 'bg-purple-50',
    textColor: 'text-purple-700',
  },
];

// ─── Products ─────────────────────────────────────────────────────────────────

export const MOCK_PRODUCTS: Product[] = [
  // Fruits & Vegetables
  {
    id: 'p1',
    name: 'Organic Bananas',
    unit: '12kg, Price',
    price: 4.99,
    image: '🍌',
    category: ProductCategory.FruitsAndVegetables,
    description:
      'Bananas are nutritious. Bananas may be good for weight loss. Bananas are good for your heart. As part of a healthy and varied diet.',
    nutrition: { calories: 89, protein: '1.1g', carbs: '23g', fat: '0.3g', fiber: '2.6g' },
    rating: 4.5,
    reviewCount: 128,
    inStock: true,
    isExclusiveOffer: true,
    isBestSelling: true,
  },
  {
    id: 'p2',
    name: 'Red Apple',
    unit: '1kg, Price',
    price: 4.99,
    image: '🍎',
    category: ProductCategory.FruitsAndVegetables,
    description:
      'Apples are nutritious. Apples may be good for weight loss. Apples are good for your heart. As part of a healthy and varied diet.',
    nutrition: { calories: 52, protein: '0.3g', carbs: '14g', fat: '0.2g', fiber: '2.4g' },
    rating: 4.8,
    reviewCount: 256,
    inStock: true,
    isExclusiveOffer: true,
    isBestSelling: true,
  },
  {
    id: 'p3',
    name: 'Bell Pepper Red',
    unit: '1kg, Price',
    price: 4.99,
    image: '🫑',
    category: ProductCategory.FruitsAndVegetables,
    description: 'Fresh red bell peppers, great for salads and stir-fry.',
    nutrition: { calories: 31, protein: '1g', carbs: '6g', fat: '0.3g', fiber: '2.1g' },
    rating: 4.3,
    reviewCount: 89,
    inStock: true,
    isBestSelling: true,
  },
  {
    id: 'p4',
    name: 'Ginger',
    unit: '250gm, Price',
    price: 2.99,
    image: '🫚',
    category: ProductCategory.FruitsAndVegetables,
    description: 'Fresh ginger root with intense aroma and flavour.',
    nutrition: { calories: 80, protein: '1.8g', carbs: '18g', fat: '0.8g', fiber: '2g' },
    rating: 4.6,
    reviewCount: 54,
    inStock: true,
  },
  {
    id: 'p5',
    name: 'Fresh Spinach',
    unit: '500g, Price',
    price: 2.49,
    originalPrice: 3.99,
    image: '🥬',
    category: ProductCategory.FruitsAndVegetables,
    description: 'Crisp fresh spinach leaves, packed with iron and vitamins.',
    nutrition: { calories: 23, protein: '2.9g', carbs: '3.6g', fat: '0.4g', fiber: '2.2g' },
    rating: 4.4,
    reviewCount: 76,
    inStock: true,
    isExclusiveOffer: true,
  },

  // Beverages
  {
    id: 'p6',
    name: 'Diet Coke',
    unit: '355ml, Price',
    price: 1.99,
    image: '🥤',
    category: ProductCategory.Beverages,
    brand: 'Cocola',
    description: 'Classic Diet Coke, zero sugar and refreshing taste.',
    nutrition: { calories: 0, protein: '0g', carbs: '0g', fat: '0g' },
    rating: 4.2,
    reviewCount: 312,
    inStock: true,
    isBestSelling: true,
  },
  {
    id: 'p7',
    name: 'Sprite Can',
    unit: '325ml, Price',
    price: 1.50,
    image: '🟢',
    category: ProductCategory.Beverages,
    brand: 'Cocola',
    description: 'Crisp lemon-lime flavoured soft drink.',
    nutrition: { calories: 140, protein: '0g', carbs: '38g', fat: '0g' },
    rating: 4.1,
    reviewCount: 198,
    inStock: true,
    isExclusiveOffer: true,
  },
  {
    id: 'p8',
    name: 'Apple & Grape Juice',
    unit: '2L, Price',
    price: 15.99,
    image: '🍇',
    category: ProductCategory.Beverages,
    brand: 'Ifad',
    description: 'Premium blend of apple and grape juice, no added sugar.',
    nutrition: { calories: 120, protein: '0.5g', carbs: '30g', fat: '0g' },
    rating: 4.5,
    reviewCount: 87,
    inStock: true,
  },
  {
    id: 'p9',
    name: 'Orange Juice',
    unit: '2L, Price',
    price: 15.99,
    image: '🍊',
    category: ProductCategory.Beverages,
    brand: 'Kazi Farmas',
    description: '100% pure squeezed orange juice with pulp.',
    nutrition: { calories: 112, protein: '1.7g', carbs: '26g', fat: '0.5g' },
    rating: 4.6,
    reviewCount: 145,
    inStock: true,
  },
  {
    id: 'p10',
    name: 'Coca Cola Can',
    unit: '325ml, Price',
    price: 4.99,
    image: '🥫',
    category: ProductCategory.Beverages,
    brand: 'Cocola',
    description: 'The classic Coca-Cola taste in a convenient can.',
    nutrition: { calories: 140, protein: '0g', carbs: '39g', fat: '0g' },
    rating: 4.3,
    reviewCount: 567,
    inStock: true,
    isBestSelling: true,
  },
  {
    id: 'p11',
    name: 'Pepsi Can',
    unit: '330ml, Price',
    price: 4.99,
    image: '🫙',
    category: ProductCategory.Beverages,
    brand: 'Individual Collection',
    description: 'Refreshing Pepsi Cola in a sleek can.',
    nutrition: { calories: 150, protein: '0g', carbs: '41g', fat: '0g' },
    rating: 4.0,
    reviewCount: 432,
    inStock: true,
  },

  // Dairy & Eggs
  {
    id: 'p12',
    name: 'Egg Chicken Red',
    unit: '4pcs, Price',
    price: 1.99,
    image: '🥚',
    category: ProductCategory.DairyAndEggs,
    brand: 'Kazi Farmas',
    description: 'Farm-fresh red chicken eggs, rich in protein.',
    nutrition: { calories: 78, protein: '6g', carbs: '0.6g', fat: '5g' },
    rating: 4.7,
    reviewCount: 234,
    inStock: true,
    isExclusiveOffer: true,
    isBestSelling: true,
  },
  {
    id: 'p13',
    name: 'Egg Chicken White',
    unit: '180g, Price',
    price: 1.50,
    image: '🍳',
    category: ProductCategory.DairyAndEggs,
    brand: 'Individual Collection',
    description: 'Premium white chicken eggs for everyday cooking.',
    nutrition: { calories: 78, protein: '6g', carbs: '0.6g', fat: '5g' },
    rating: 4.5,
    reviewCount: 189,
    inStock: true,
  },
  {
    id: 'p14',
    name: 'Fresh Milk',
    unit: '1L, Price',
    price: 3.49,
    image: '🥛',
    category: ProductCategory.DairyAndEggs,
    brand: 'Kazi Farmas',
    description: 'Full cream fresh milk, pasteurised and homogenised.',
    nutrition: { calories: 61, protein: '3.2g', carbs: '4.8g', fat: '3.3g' },
    rating: 4.8,
    reviewCount: 412,
    inStock: true,
    isBestSelling: true,
  },

  // Noodles & Pasta
  {
    id: 'p15',
    name: 'Egg Pasta',
    unit: '30gm, Price',
    price: 15.99,
    image: '🍝',
    category: ProductCategory.Noodles,
    brand: 'Individual Collection',
    description: 'Classic Italian-style egg pasta, cook in 8 minutes.',
    nutrition: { calories: 371, protein: '13g', carbs: '72g', fat: '3g' },
    rating: 4.2,
    reviewCount: 56,
    inStock: true,
  },
  {
    id: 'p16',
    name: 'Egg Noodles',
    unit: '2L, Price',
    price: 15.99,
    image: '🍜',
    category: ProductCategory.Noodles,
    brand: 'Cocola',
    description: 'Smooth egg noodles, perfect for stir-fry and soups.',
    nutrition: { calories: 384, protein: '14g', carbs: '71g', fat: '4g' },
    rating: 4.0,
    reviewCount: 43,
    inStock: true,
  },

  // Meat & Fish
  {
    id: 'p17',
    name: 'Beef Bone',
    unit: '1kg, Price',
    price: 4.99,
    image: '🍖',
    category: ProductCategory.MeatAndFish,
    description: 'Fresh beef bone for rich broths and soups.',
    nutrition: { calories: 250, protein: '20g', carbs: '0g', fat: '18g' },
    rating: 4.3,
    reviewCount: 67,
    inStock: true,
  },
  {
    id: 'p18',
    name: 'Broiler Chicken',
    unit: '1kg, Price',
    price: 4.99,
    image: '🍗',
    category: ProductCategory.MeatAndFish,
    description: 'Fresh whole broiler chicken, cleaned and ready to cook.',
    nutrition: { calories: 239, protein: '27g', carbs: '0g', fat: '14g' },
    rating: 4.6,
    reviewCount: 189,
    inStock: true,
    isBestSelling: true,
  },

  // Bakery & Snacks
  {
    id: 'p19',
    name: 'Mayonnais Eggless',
    unit: '200g, Price',
    price: 3.99,
    image: '🫙',
    category: ProductCategory.BakeryAndSnacks,
    brand: 'Individual Collection',
    description: 'Creamy eggless mayonnaise for sandwiches and salads.',
    nutrition: { calories: 290, protein: '0.4g', carbs: '1.4g', fat: '30g' },
    rating: 4.1,
    reviewCount: 34,
    inStock: true,
  },
  {
    id: 'p20',
    name: 'Whole Wheat Bread',
    unit: '400g, Price',
    price: 2.99,
    originalPrice: 3.99,
    image: '🍞',
    category: ProductCategory.BakeryAndSnacks,
    brand: 'Kazi Farmas',
    description: 'Soft whole wheat bread, baked fresh daily.',
    nutrition: { calories: 247, protein: '8g', carbs: '48g', fat: '3g', fiber: '4g' },
    rating: 4.4,
    reviewCount: 123,
    inStock: true,
    isExclusiveOffer: true,
  },

  // Pulses
  {
    id: 'p21',
    name: 'Red Lentils',
    unit: '500g, Price',
    price: 2.49,
    image: '🫘',
    category: ProductCategory.Pulses,
    description: 'Premium red lentils, perfect for dal and soups.',
    nutrition: { calories: 352, protein: '25g', carbs: '63g', fat: '1g', fiber: '11g' },
    rating: 4.5,
    reviewCount: 98,
    inStock: true,
  },

  // Rice
  {
    id: 'p22',
    name: 'Basmati Rice',
    unit: '2kg, Price',
    price: 7.99,
    image: '🌾',
    category: ProductCategory.Rice,
    description: 'Long-grain premium basmati rice from the foothills of the Himalayas.',
    nutrition: { calories: 365, protein: '7g', carbs: '80g', fat: '0.5g' },
    rating: 4.8,
    reviewCount: 312,
    inStock: true,
    isBestSelling: true,
  },
];

// ─── Zones ────────────────────────────────────────────────────────────────────

export const MOCK_ZONES: Zone[] = [
  {
    id: 'z1',
    name: 'Banasree',
    areas: [
      { id: 'a1', name: 'Block A', zoneId: 'z1' },
      { id: 'a2', name: 'Block B', zoneId: 'z1' },
      { id: 'a3', name: 'Block C', zoneId: 'z1' },
      { id: 'a4', name: 'Block D', zoneId: 'z1' },
    ],
  },
  {
    id: 'z2',
    name: 'Gulshan',
    areas: [
      { id: 'a5', name: 'Gulshan 1', zoneId: 'z2' },
      { id: 'a6', name: 'Gulshan 2', zoneId: 'z2' },
    ],
  },
  {
    id: 'z3',
    name: 'Dhanmondi',
    areas: [
      { id: 'a7', name: 'Dhanmondi 27', zoneId: 'z3' },
      { id: 'a8', name: 'Dhanmondi 32', zoneId: 'z3' },
    ],
  },
  {
    id: 'z4',
    name: 'Mirpur',
    areas: [
      { id: 'a9', name: 'Mirpur 1', zoneId: 'z4' },
      { id: 'a10', name: 'Mirpur 10', zoneId: 'z4' },
      { id: 'a11', name: 'Mirpur 12', zoneId: 'z4' },
    ],
  },
];

// ─── Simulated API helpers ────────────────────────────────────────────────────

export const fetchProducts = (): Promise<Product[]> =>
  new Promise((resolve) =>
    setTimeout(() => resolve(MOCK_PRODUCTS), 1200)
  );

export const fetchProductById = (id: string): Promise<Product | undefined> =>
  new Promise((resolve) =>
    setTimeout(
      () => resolve(MOCK_PRODUCTS.find((p) => p.id === id)),
      800
    )
  );

export const fetchZones = (): Promise<Zone[]> =>
  new Promise((resolve) => setTimeout(() => resolve(MOCK_ZONES), 500));
